config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'sessions#show'

  resources :makes, only: %i[index new edit create update destroy]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/make.rb
# frozen_string_literal: true

class Make < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  add_flash_types :primary, :secondary, :success, :danger, :warning, :info, :light, :dark
end

app/controllers/makes_controller.rb
# frozen_string_literal: true

class MakesController < ApplicationController
  before_action :initialize_make, only: %i[new create]
  before_action :find_make, only: %i[edit update destroy]

  def index
    @makes = Make.order(:name)
  end

  def new; end

  def edit; end

  def create
    @make.update! make_params
    redirect_to makes_path, success: t('.success')
  rescue ActiveRecord::RecordInvalid
    flash.now[:danger] = @make.errors.full_messages.to_sentence
    render :new
  end

  def update
    @make.update! make_params
    redirect_to makes_path, success: t('.success')
  rescue ActiveRecord::RecordInvalid
    flash.now[:danger] = @make.errors.full_messages.to_sentence
    render :edit
  end

  def destroy
    @make.destroy!
    redirect_to makes_path, success: t('.success')
  rescue ActiveRecord::RecordNotDestroyed
    redirect_to makes_path, danger: @make.errors.full_messages.to_sentence
  end

  private

  def initialize_make
    @make = Make.new
  end

  def find_make
    @make = Make.find(params[:id])
  end

  def make_params
    params.fetch(:make, {}).permit(:name)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def show; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/_alert.html.haml
:ruby
  options = local_assigns.clone
  variant = options.delete :variant
  variant = 'info' if variant.to_s == 'notice'
  variant = 'danger' if variant.to_s == 'alert'
  options[:class] = [options[:class],
                     'alert',
                     "alert-#{variant}",
                     'alert-dismissable',
                     'fade',
                     'show'].flatten
= tag.div(**options) do
  .d-flex.justify-content-between.align-items-center.gap-3
    %div= yield
    = button_tag '', type: 'button', class: 'btn-close', data: { 'bs-dismiss': 'alert' }, 'aria-label': 'Close'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Dealership
    %meta{ name: 'viewport', content: 'width=device-width,initial-scale=1' }
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true
  %body
    %header
      %nav.navbar.navbar-expand-sm.bg-light.border-bottom
        .container-fluid
          %span.navbar-brand.mb-0.h1 Dealership
          = button_tag type: 'button',
                       class: 'navbar-toggler',
                       data: { 'bs-target': '#navbar-content', 'bs-toggle': 'collapse' },
                       aria: { controls: 'navbar-content', expanded: 'false', label: 'Toggle' } do
            %span.navbar-toggler-icon
          #navbar-content.collapse.navbar-collapse
            %ul.navbar-nav.mb-2.mb-sm-0.me-auto
              %li.nav-item
                = link_to 'Home',
                          root_path,
                          class: ['nav-link', current_page?(root_path).presence && 'active'],
                          'aria-current': current_page?(root_path) && 'page'
              %li.nav-item
                = link_to 'Makes',
                          makes_path,
                          class: ['nav-link', (controller_name == 'makes') ? 'active' : nil],
                          'aria-current': (controller_name == 'makes') ? 'page' : false
      .container.mt-3
        - flash.each do |variant, content|
          = render layout: 'layouts/alert', locals: { variant: variant } do
            = content
    %main
      = yield

app/views/makes/_fields.html.haml
.mb-3
  = fields.label :name, class: 'form-label'
  = fields.text_field :name, required: true, class: 'form-control'

app/views/makes/_list_group_item.html.haml
.list-group-item
  .lead.d-flex.justify-content-between.align-items-center.flex-nowrap
    = list_group_item.name
    .d-flex.gap-1
      = link_to edit_make_path(list_group_item), title: 'Edit', class: 'btn btn-link' do
        %i.fa-solid.fa-edit
      = link_to make_path(list_group_item),
                title: 'Delete',
                class: 'btn btn-link',
                data: { 'turbo-confirm': 'Are you sure you want to delete this make?', 'turbo-method': :delete } do
        %i.fa-solid.fa-trash

app/views/makes/edit.html.haml
%section.container
  .d-flex.justify-content-between.align-items-end.flex-nowrap
    %h1.mb-0 Edit Make
    = link_to makes_path, title: 'Cancel', class: 'btn btn-link' do
      %i.fa-solid.fa-times
  %hr
  = form_with model: @make do |f|
    = render partial: 'fields', object: f
    = f.submit class: 'btn btn-primary'

app/views/makes/index.html.haml
%section.container
  .d-flex.justify-content-between.align-items-end.flex-nowrap
    %h1.mb-0 Makes
    = link_to new_make_path, title: 'Add', class: 'btn btn-link' do
      %i.fa-solid.fa-plus
  %hr
  - if @makes.present?
    .list-group.list-group-flush
      = render partial: 'list_group_item', collection: @makes
  - else
    No makes found.

app/views/makes/new.html.haml
%section.container
  .d-flex.justify-content-between.align-items-end.flex-nowrap
    %h1.mb-0 New Make
    = link_to makes_path, title: 'Cancel', class: 'btn btn-link' do
      %i.fa-solid.fa-times
  %hr
  = form_with model: @make do |f|
    = render partial: 'fields', object: f
    = f.submit class: 'btn btn-primary'